# Generated by Django 3.2.8 on 2021-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_desc', models.TextField(blank=True, max_length=500)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_dis_price', models.FloatField(blank=True, null=True)),
                ('product_qty_type', models.CharField(choices=[('250gm', '250 Grams'), ('500gm', '500 Grams'), ('1000gm', '1000 Grams'), ('2000gm', '2000 Grams'), ('3000gm', '3000 Grams'), ('1PC', '1 Pc'), ('12PC', '12 Pc')], max_length=12)),
                ('product_qty', models.IntegerField()),
                ('product_type', models.IntegerField()),
                ('product_photo', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
