# Generated by Django 3.2.8 on 2021-11-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('V', 'Vegitables'), ('F', 'Fruits')], max_length=1),
        ),
    ]
